# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0005_auto_20171203_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event',
        ),
    ]
