# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0007_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default=0, max_length=280),
            preserve_default=False,
        ),
    ]
