# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0009_auto_20171204_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.IntegerField(choices=[('Soccer', 'Soccer'), ('Football', 'Football'), ('Baseball', 'Baseball'), ('Wiffleball', 'Wiffleball'), ('Ultimate Frisbee', 'Ultimate Frisbee')], default=1),
        ),
    ]
