# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0010_auto_20171206_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportsapp.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Football', 'Football'), ('Baseball', 'Baseball'), ('Wiffleball', 'Wiffleball'), ('Ultimate Frisbee', 'Ultimate Frisbee'), ('Basketball', 'Basketball'), ('Disc Golf', 'Disc Golf')], max_length=40),
        ),
    ]
