# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0011_auto_20171211_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
    ]
