# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0012_remove_team_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='events',
            field=models.ManyToManyField(to='sportsapp.event'),
        ),
    ]
