# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0013_team_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='sport',
        ),
        migrations.RemoveField(
            model_name='team',
            name='events',
        ),
        migrations.AddField(
            model_name='team',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportsapp.event'),
            preserve_default=False,
        ),
    ]
