# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0014_auto_20171211_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='events',
        ),
    ]
