# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0015_remove_team_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sport',
            new_name='event',
        ),
    ]
